# -*- coding: utf-8 -*-
"""2303A52435_assignment1.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHGqqMQJs9aHxE5RKijWeQfrnyLSXyvd
"""

a=[1,2,3,4]
b=[5,6,7,8]

import numpy as np

a=np.array(a)
b=np.array(b)
print(a+b)

print(np.mean(a))

print(np.mean(b))

print(np.var(a))

print(np.var(b))

print(np.average(a))

print(np.average(b))

print(np.std(a))

print(np.std(b))

print(np.max(a)-np.min(a))

print(np.max(b)-np.min(b))

m=[[1,2,3],[4,5,6],[7,8,9]]

print(m)

m=np.array(m)
print(m)

g=[[2,3,4],[5,6,7],[8,9,0]]

m=np.array(m)
g=np.array(g)
print(m+g)

print(np.transpose(g))

print(np.matmul(m,g))

print(np.sin(30))

print(np.linalg.matrix_rank(g))

print(np.linalg.det(g))

import matplotlib.pyplot as plt

x=[1,2,3,4,5,6,7,8]
y=[4,5,6,7,8,9,1,2]
plt.plot(x,y)
plt.show()

x=[4,5,6,7,8,9,1,2]
y=[1,2,3,4,5,6,7,8]
plt.scatter(x,y)
plt.show()

x=[4,5,6,7,8,9,1,2]
y=[1,2,3,4,5,6,7,8]
plt.hist(x)
plt.show()